### ISSUE TITLE
[R7SP2] As an admin, depuis la navbar, rubrique Administration, l'entrée gestion des blocs éditoriaux ne pointe pas vers la bonne page

### ISSUE THREAD

**Issue by sfr-ans** [cybersante/Blacklist_tools#1]
- [ ] Ne plus pointer vers la page de gestion des rapports mais vers la page de gestion des blocs éditoriaux

**Comment by lprat** [comment]
Avez vous fait une erreur dans l'issue?

**Comment by sfr-ans** [comment]
Bonsoir, c'est effectivement une erreur de notre part.
